// ACLCloudFreeBotToolKit
// Copyright (C) 2026 MessyMidi
//
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPLv3 Section 7:
// see /ADDITIONAL_TERMS.md

package main

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunAveragesSamplesPerWord(t *testing.T) {
	images := t.TempDir()
	writeSample(t, filepath.Join(images, "Bot.png"), 10)
	writeSample(t, filepath.Join(images, "Bot2.png"), 12)
	writeSample(t, filepath.Join(images, "Cloud.png"), 40)
	if err := os.WriteFile(filepath.Join(images, "notes.txt"), []byte("ignored"), 0o644); err != nil {
		t.Fatal(err)
	}

	output := filepath.Join(t.TempDir(), "captcha_solver_ref.go")
	if err := run(images, output); err != nil {
		t.Fatal(err)
	}
	source, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	text := string(source)
	for _, want := range []string{"// Code generated by go run ./genref; DO NOT EDIT.", `word: "Bot"`, `word: "Cloud"`, "package renew"} {
		if !strings.Contains(text, want) {
			t.Errorf("generated source is missing %q", want)
		}
	}
	if strings.Count(text, "{word:") != 2 {
		t.Errorf("expected one entry per word:\n%s", text)
	}
	// Bot.png and Bot2.png each have a 10-pixel-high ink column at a different
	// position, so the average has 5.0 at both positions.
	if !strings.Contains(text, "5.0000000000") {
		t.Errorf("Bot samples were not averaged:\n%s", text)
	}
}

func TestRunRejectsAnEmptyDirectory(t *testing.T) {
	if err := run(t.TempDir(), filepath.Join(t.TempDir(), "out.go")); err == nil {
		t.Fatal("run succeeded without samples")
	}
}

// writeSample stores a white 200x46 image with a 10-pixel black column at x.
func writeSample(t *testing.T, path string, x int) {
	t.Helper()
	img := image.NewGray(image.Rect(0, 0, 200, 46))
	for py := 0; py < 46; py++ {
		for px := 0; px < 200; px++ {
			img.SetGray(px, py, color.Gray{Y: 255})
		}
	}
	for py := 10; py < 20; py++ {
		img.SetGray(x, py, color.Gray{Y: 0})
	}
	var data bytes.Buffer
	if err := png.Encode(&data, img); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}
}
