// ACLCloudFreeBotToolKit
// Copyright (C) 2026 MessyMidi
//
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPLv3 Section 7:
// see /ADDITIONAL_TERMS.md

// Command genref rebuilds internal/renew/captcha_solver_ref.go from labelled
// CAPTCHA option images.
//
// The samples are ACLClouds CAPTCHA images and are not part of the
// repository. Keep them in a local directory as PNG files named after the
// word they show, optionally followed by a sample number (Bot.png,
// Bot2.png, ...), then run from internal/renew:
//
//	go run ./genref -images /path/to/samples
//
// The profiles are computed with the same code the solver uses at runtime.
// The first reference file was produced by a Python script that converted
// the images to grayscale with PIL, which rounds a few pixels differently,
// so regenerating it from the same samples changes some values slightly.
// Both versions recognised all 159 original samples.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/MessyMidi/ACLCloudFreeBotToolKit/internal/renew"
)

const header = `// ACLCloudFreeBotToolKit
// Copyright (C) 2026 MessyMidi
//
// SPDX-License-Identifier: AGPL-3.0-only
// Additional terms under AGPLv3 Section 7:
// see /ADDITIONAL_TERMS.md

// Code generated by go run ./genref; DO NOT EDIT.
// Source: labelled CAPTCHA samples kept outside the repository.

package renew

// precomputedWord holds averaged column and row profiles for one word.
type precomputedWord struct {
	word       string
	colProfile []float64
	rowProfile []float64
}

// precomputedRef is the reference database baked into the binary.
// Computed from labeled captcha samples at build time.
var precomputedRef = []precomputedWord{
`

type samples struct {
	cols [][]float64
	rows [][]float64
}

func main() {
	log.SetFlags(0)
	images := flag.String("images", "", "directory of labelled CAPTCHA option PNG files")
	output := flag.String("o", "captcha_solver_ref.go", "generated Go file")
	flag.Parse()
	if *images == "" {
		log.Fatal("usage: go run ./genref -images DIR [-o captcha_solver_ref.go]")
	}
	if err := run(*images, *output); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s", *output)
}

func run(images, output string) error {
	entries, err := os.ReadDir(images)
	if err != nil {
		return err
	}
	words := map[string]*samples{}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.EqualFold(filepath.Ext(name), ".png") {
			continue
		}
		word := strings.TrimRight(strings.TrimSuffix(name, filepath.Ext(name)), "0123456789")
		if word == "" {
			return fmt.Errorf("%s: file name does not start with a word", name)
		}
		data, err := os.ReadFile(filepath.Join(images, name))
		if err != nil {
			return err
		}
		cols, rows, err := renew.CaptchaProfiles(data)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		if words[word] == nil {
			words[word] = &samples{}
		}
		words[word].cols = append(words[word].cols, cols)
		words[word].rows = append(words[word].rows, rows)
	}
	if len(words) == 0 {
		return fmt.Errorf("no PNG samples found in %s", images)
	}

	names := make([]string, 0, len(words))
	for word := range words {
		names = append(names, word)
	}
	slices.Sort(names)

	var source bytes.Buffer
	source.WriteString(header)
	for _, word := range names {
		fmt.Fprintf(&source, "\t{word: %q, colProfile: %s, rowProfile: %s},\n",
			word, sliceLiteral(average(words[word].cols)), sliceLiteral(average(words[word].rows)))
		log.Printf("%s: %d samples", word, len(words[word].cols))
	}
	source.WriteString("}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(output, formatted, 0o644)
}

// average returns the element-wise mean of equally long profiles, rounded
// to float32 precision to keep the generated file compact.
func average(profiles [][]float64) []float64 {
	mean := make([]float64, len(profiles[0]))
	for _, profile := range profiles {
		for i, value := range profile {
			mean[i] += value
		}
	}
	for i := range mean {
		mean[i] = float64(float32(mean[i] / float64(len(profiles))))
	}
	return mean
}

func sliceLiteral(values []float64) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = fmt.Sprintf("%.10f", value)
	}
	return "[]float64{" + strings.Join(parts, ", ") + "}"
}
